'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property XYVOXEL() As Double
            Get
                Return CType(Me("XYVOXEL"),Double)
            End Get
            Set
                Me("XYVOXEL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("6")>  _
        Public Property ZVOXEL() As Double
            Get
                Return CType(Me("ZVOXEL"),Double)
            End Get
            Set
                Me("ZVOXEL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NORMALIZE_IMAGE() As Boolean
            Get
                Return CType(Me("NORMALIZE_IMAGE"),Boolean)
            End Get
            Set
                Me("NORMALIZE_IMAGE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property SCALEBARLENGTH() As Integer
            Get
                Return CType(Me("SCALEBARLENGTH"),Integer)
            End Get
            Set
                Me("SCALEBARLENGTH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property STORELENSLOCATIONS() As Boolean
            Get
                Return CType(Me("STORELENSLOCATIONS"),Boolean)
            End Get
            Set
                Me("STORELENSLOCATIONS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("20")>  _
        Public Property STEPVEL() As Decimal
            Get
                Return CType(Me("STEPVEL"),Decimal)
            End Get
            Set
                Me("STEPVEL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property STEPACC() As Decimal
            Get
                Return CType(Me("STEPACC"),Decimal)
            End Get
            Set
                Me("STEPACC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("25")>  _
        Public Property STEPWIDTH() As Decimal
            Get
                Return CType(Me("STEPWIDTH"),Decimal)
            End Get
            Set
                Me("STEPWIDTH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property STEPWAIT() As Decimal
            Get
                Return CType(Me("STEPWAIT"),Decimal)
            End Get
            Set
                Me("STEPWAIT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("25")>  _
        Public Property LENSSTEPWIDTH() As Decimal
            Get
                Return CType(Me("LENSSTEPWIDTH"),Decimal)
            End Get
            Set
                Me("LENSSTEPWIDTH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PROJECTNR() As String
            Get
                Return CType(Me("PROJECTNR"),String)
            End Get
            Set
                Me("PROJECTNR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property EXPERIMENT() As String
            Get
                Return CType(Me("EXPERIMENT"),String)
            End Get
            Set
                Me("EXPERIMENT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SPECIMEN() As String
            Get
                Return CType(Me("SPECIMEN"),String)
            End Get
            Set
                Me("SPECIMEN") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PERFUSIONDATE() As String
            Get
                Return CType(Me("PERFUSIONDATE"),String)
            End Get
            Set
                Me("PERFUSIONDATE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DETAIL() As String
            Get
                Return CType(Me("DETAIL"),String)
            End Get
            Set
                Me("DETAIL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("488 nm")>  _
        Public Property WAVELENGTH() As String
            Get
                Return CType(Me("WAVELENGTH"),String)
            End Get
            Set
                Me("WAVELENGTH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("200 mW")>  _
        Public Property LASERPOWER() As String
            Get
                Return CType(Me("LASERPOWER"),String)
            End Get
            Set
                Me("LASERPOWER") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Olympus")>  _
        Public Property MICROSCOPE() As String
            Get
                Return CType(Me("MICROSCOPE"),String)
            End Get
            Set
                Me("MICROSCOPE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10x")>  _
        Public Property OBJECTIVE() As String
            Get
                Return CType(Me("OBJECTIVE"),String)
            End Get
            Set
                Me("OBJECTIVE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1x")>  _
        Public Property POSTMAG() As String
            Get
                Return CType(Me("POSTMAG"),String)
            End Get
            Set
                Me("POSTMAG") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("new system")>  _
        Public Property CYLLENS() As String
            Get
                Return CType(Me("CYLLENS"),String)
            End Get
            Set
                Me("CYLLENS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("none")>  _
        Public Property SLIT() As String
            Get
                Return CType(Me("SLIT"),String)
            End Get
            Set
                Me("SLIT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property COMMENTS() As String
            Get
                Return CType(Me("COMMENTS"),String)
            End Get
            Set
                Me("COMMENTS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property RECMODE() As Integer
            Get
                Return CType(Me("RECMODE"),Integer)
            End Get
            Set
                Me("RECMODE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1000")>  _
        Public Property NIMAGES() As Integer
            Get
                Return CType(Me("NIMAGES"),Integer)
            End Get
            Set
                Me("NIMAGES") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property STARTNUM() As Integer
            Get
                Return CType(Me("STARTNUM"),Integer)
            End Get
            Set
                Me("STARTNUM") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property SCANMODE() As Integer
            Get
                Return CType(Me("SCANMODE"),Integer)
            End Get
            Set
                Me("SCANMODE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CAMERAMODE() As Integer
            Get
                Return CType(Me("CAMERAMODE"),Integer)
            End Get
            Set
                Me("CAMERAMODE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property CAMERATYPE() As Integer
            Get
                Return CType(Me("CAMERATYPE"),Integer)
            End Get
            Set
                Me("CAMERATYPE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property CAMERABACKGROUND() As UShort
            Get
                Return CType(Me("CAMERABACKGROUND"),UShort)
            End Get
            Set
                Me("CAMERABACKGROUND") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SAVEFULLRANGETIFFS() As Boolean
            Get
                Return CType(Me("SAVEFULLRANGETIFFS"),Boolean)
            End Get
            Set
                Me("SAVEFULLRANGETIFFS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property CAMERAROTATED() As Boolean
            Get
                Return CType(Me("CAMERAROTATED"),Boolean)
            End Get
            Set
                Me("CAMERAROTATED") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("90")>  _
        Public Property HDRICLIP() As Integer
            Get
                Return CType(Me("HDRICLIP"),Integer)
            End Get
            Set
                Me("HDRICLIP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property HDRION() As Boolean
            Get
                Return CType(Me("HDRION"),Boolean)
            End Get
            Set
                Me("HDRION") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property HRIratio() As Integer
            Get
                Return CType(Me("HRIratio"),Integer)
            End Get
            Set
                Me("HRIratio") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property UNDEREXPLIMIT() As Integer
            Get
                Return CType(Me("UNDEREXPLIMIT"),Integer)
            End Get
            Set
                Me("UNDEREXPLIMIT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("99")>  _
        Public Property OVEREXPLIMIT() As Integer
            Get
                Return CType(Me("OVEREXPLIMIT"),Integer)
            End Get
            Set
                Me("OVEREXPLIMIT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property EXPOSURE() As Double
            Get
                Return CType(Me("EXPOSURE"),Double)
            End Get
            Set
                Me("EXPOSURE") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.UMController.My.MySettings
            Get
                Return Global.UMController.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
